#!/usr/bin/env python3
"""
Generate neutrino transfer function ratio table R_nu(k,a) = T_nu/T_cb
for the cuRAMSES linear response neutrino implementation.

Uses CAMB to compute matter transfer functions at multiple redshifts.
Output: ASCII table readable by neutrino_commons.f90

Usage:
    python generate_neutrino_table.py [output_file]

Default output: neutrino_table.dat
"""

import sys
import numpy as np

try:
    import camb
except ImportError:
    print("ERROR: CAMB not installed. Install with: pip install camb")
    sys.exit(1)


def generate_neutrino_table(
    output_file="neutrino_table.dat",
    # Cosmological parameters (Planck 2018 + minimal neutrino mass)
    omega_b=0.0486,
    omega_m=0.3089,
    h0=0.6774,
    sum_mnu=0.06,     # eV, minimal normal hierarchy
    n_s=0.9667,
    A_s=2.142e-9,
    # Table grid
    nk=200,
    na=50,
    k_min=1.0e-4,      # h/Mpc
    k_max=10.0,         # h/Mpc
    a_min=0.01,         # scale factor (z=99)
    a_max=1.0,          # scale factor (z=0)
):
    """Generate R_nu(k,a) = T_nu(k,a) / T_cb(k,a) table."""

    print(f"CAMB version: {camb.__version__}")
    print(f"Parameters: omega_m={omega_m}, omega_b={omega_b}, h0={h0}")
    print(f"  sum_mnu={sum_mnu} eV")
    print(f"  Table: {nk} k-points x {na} a-points")

    # k and a grids (log-spaced)
    k_arr = np.logspace(np.log10(k_min), np.log10(k_max), nk)  # h/Mpc
    a_arr = np.logspace(np.log10(a_min), np.log10(a_max), na)
    z_arr = 1.0 / a_arr - 1.0  # redshifts (descending in a, ascending in z)

    # omega_cdm = omega_m - omega_b - omega_nu
    omega_nu = sum_mnu / (93.14 * h0**2)
    omega_cdm = omega_m - omega_b - omega_nu
    print(f"  omega_nu={omega_nu:.6f}, omega_cdm={omega_cdm:.6f}")

    # Setup CAMB parameters
    pars = camb.CAMBparams()
    pars.set_cosmology(
        H0=h0 * 100,
        ombh2=omega_b * h0**2,
        omch2=omega_cdm * h0**2,
        mnu=sum_mnu,
        neutrino_hierarchy="degenerate",
    )
    pars.InitPower.set_params(ns=n_s, As=A_s)

    # We need transfer functions at each redshift
    pars.set_matter_power(redshifts=sorted(z_arr.tolist(), reverse=True), kmax=k_max * 1.2)
    pars.WantTransfer = True

    results = camb.get_results(pars)

    # R_nu(k,a) matrix: nk x na
    R_nu = np.zeros((nk, na))

    for ia, z_val in enumerate(z_arr):
        # Get transfer functions
        trans = results.get_matter_transfer_data()

        # Find the redshift index in CAMB output (sorted descending in z)
        z_sorted = sorted(z_arr.tolist(), reverse=True)
        iz_camb = z_sorted.index(z_val)

        # Transfer function variables:
        #   trans.transfer_data[var_index, k_index, z_index]
        # Variable indices: 0=CDM, 1=baryon, 2=photon, 3=massless nu,
        #                   4=massive nu, 5=total, 6=no-nu, 7=total de
        # CDM+baryon weighted transfer: use model.Transfer_cdm (=0) and Transfer_b (=1)
        # Or use Transfer_nonu (=6) for CDM+baryon combined

        k_camb = trans.transfer_data[0, :, 0]  # k/h values (same for all z)

        # T_cb = CDM+baryon (no neutrino) transfer
        T_cb = trans.transfer_data[6, :, iz_camb]  # Transfer_nonu

        # T_nu = massive neutrino transfer
        T_nu = trans.transfer_data[4, :, iz_camb]  # Transfer_nu

        # Interpolate to our k grid
        T_cb_interp = np.interp(np.log10(k_arr), np.log10(k_camb), T_cb)
        T_nu_interp = np.interp(np.log10(k_arr), np.log10(k_camb), T_nu)

        # R_nu = T_nu / T_cb
        # Avoid division by zero
        mask = np.abs(T_cb_interp) > 1e-30
        R_nu[mask, ia] = T_nu_interp[mask] / T_cb_interp[mask]
        R_nu[~mask, ia] = 0.0

    # Write output table
    print(f"Writing table to {output_file}")
    with open(output_file, "w") as f:
        f.write(f"# Neutrino transfer function ratio R_nu(k,a) = T_nu/T_cb\n")
        f.write(f"# Generated by generate_neutrino_table.py using CAMB {camb.__version__}\n")
        f.write(f"# Cosmology: omega_m={omega_m} omega_b={omega_b} h0={h0} sum_mnu={sum_mnu}eV\n")
        f.write(f"# omega_nu={omega_nu:.6f}\n")
        f.write(f"# nk  na\n")
        f.write(f"{nk}  {na}\n")
        f.write(f"# k values (h/Mpc), log-spaced\n")
        for i, k in enumerate(k_arr):
            f.write(f"{k:.6e}")
            if (i + 1) % 10 == 0 or i == nk - 1:
                f.write("\n")
            else:
                f.write("  ")
        f.write(f"# a values (scale factor), log-spaced\n")
        for i, a in enumerate(a_arr):
            f.write(f"{a:.6e}")
            if (i + 1) % 10 == 0 or i == na - 1:
                f.write("\n")
            else:
                f.write("  ")
        f.write(f"# R_nu(k,a) matrix: nk rows x na columns\n")
        for ik in range(nk):
            for ia in range(na):
                f.write(f"{R_nu[ik, ia]:.6e}")
                if (ia + 1) % 10 == 0 or ia == na - 1:
                    f.write("\n")
                else:
                    f.write("  ")

    print(f"Done. Table shape: {nk} x {na}")
    print(f"k range: [{k_arr[0]:.2e}, {k_arr[-1]:.2e}] h/Mpc")
    print(f"a range: [{a_arr[0]:.4f}, {a_arr[-1]:.4f}]")
    print(f"R_nu range: [{R_nu.min():.4f}, {R_nu.max():.4f}]")


if __name__ == "__main__":
    outfile = sys.argv[1] if len(sys.argv) > 1 else "neutrino_table.dat"
    generate_neutrino_table(output_file=outfile)
