#!/usr/bin/env python3
"""
Generate dark energy transfer function ratio table R_DE(k,a) = delta_DE/delta_m
for the cuRAMSES linear response DE perturbation implementation.

Uses CAMB to compute matter and dark energy perturbations at multiple redshifts.
Output: ASCII table readable by dark_energy_commons.f90 (same format as neutrino_table.dat)

Usage:
    python generate_de_table.py [options] [-o output_file]

Examples:
    # c_s^2 = 0 clustering DE (R_DE is k-independent)
    python generate_de_table.py --w0=-0.9 --wa=0.1 --cs2=0.0 -o de_table_cs0.dat

    # c_s^2 = 1 smooth DE (R_DE ~ 0 at small scales)
    python generate_de_table.py --w0=-0.9 --wa=0.1 --cs2=1.0 -o de_table_cs1.dat

    # LCDM check (R_DE ~ 0 since 1+w = 0)
    python generate_de_table.py --w0=-1.0 --wa=0.0 --cs2=0.0 -o de_table_lcdm.dat
"""

import sys
import argparse
import numpy as np

try:
    import camb
except ImportError:
    print("ERROR: CAMB not installed. Install with: pip install camb")
    sys.exit(1)


def generate_de_table(
    output_file="de_table.dat",
    # DE parameters
    w0=-0.9,
    wa=0.1,
    cs2_de=0.0,
    # Cosmological parameters (Planck 2018)
    omega_b=0.0486,
    omega_m=0.3089,
    h0=0.6774,
    n_s=0.9667,
    A_s=2.142e-9,
    # Table grid
    nk=200,
    na=50,
    k_min=1.0e-4,      # h/Mpc
    k_max=10.0,         # h/Mpc
    a_min=0.01,         # scale factor (z=99)
    a_max=1.0,          # scale factor (z=0)
):
    """Generate R_DE(k,a) = delta_DE(k,a) / delta_m(k,a) table."""

    print(f"CAMB version: {camb.__version__}")
    print(f"DE parameters: w0={w0}, wa={wa}, cs2_de={cs2_de}")
    print(f"Cosmology: omega_m={omega_m}, omega_b={omega_b}, h0={h0}")
    print(f"Table: {nk} k-points x {na} a-points")

    # k and a grids (log-spaced)
    k_arr = np.logspace(np.log10(k_min), np.log10(k_max), nk)  # h/Mpc
    a_arr = np.logspace(np.log10(a_min), np.log10(a_max), na)
    z_arr = 1.0 / a_arr - 1.0  # redshifts

    omega_cdm = omega_m - omega_b
    print(f"  omega_cdm={omega_cdm:.6f}")

    # Setup CAMB parameters
    pars = camb.CAMBparams()
    pars.set_cosmology(
        H0=h0 * 100,
        ombh2=omega_b * h0**2,
        omch2=omega_cdm * h0**2,
        mnu=0.0,  # no massive neutrinos for DE-only test
    )
    pars.InitPower.set_params(ns=n_s, As=A_s)

    # Set CPL dark energy with specified sound speed
    pars.DarkEnergy = camb.dark_energy.DarkEnergyFluid(w=w0, wa=wa, cs2=cs2_de)

    # Request perturbation evolution
    pars.set_matter_power(redshifts=sorted(z_arr.tolist(), reverse=True), kmax=k_max * 1.5)
    pars.WantTransfer = True

    print("Running CAMB...")
    results = camb.get_results(pars)

    # Use get_redshift_evolution to get delta_cdm, delta_baryon, delta_de
    # q_arr in Mpc^-1 (not h/Mpc), so convert
    q_arr = k_arr * h0  # Mpc^-1

    R_DE = np.zeros((nk, na))

    for ia, z_val in enumerate(z_arr):
        ev = results.get_redshift_evolution(q_arr, [z_val],
                                            ['delta_cdm', 'delta_baryon', 'delta_de'])
        # ev shape: (nk, 1, 3)
        delta_cdm = ev[:, 0, 0]
        delta_b   = ev[:, 0, 1]
        delta_de  = ev[:, 0, 2]

        # Matter = CDM + baryon (weighted)
        delta_m = (omega_cdm * delta_cdm + omega_b * delta_b) / omega_m

        # R_DE = delta_de / delta_m
        mask = np.abs(delta_m) > 1e-30
        R_DE[mask, ia] = delta_de[mask] / delta_m[mask]
        R_DE[~mask, ia] = 0.0

    # Write output table (same format as neutrino_table.dat)
    print(f"Writing table to {output_file}")
    with open(output_file, "w") as f:
        f.write(f"# Dark energy transfer function ratio R_DE(k,a) = delta_DE/delta_m\n")
        f.write(f"# Generated by generate_de_table.py using CAMB {camb.__version__}\n")
        f.write(f"# DE: w0={w0} wa={wa} cs2_de={cs2_de}\n")
        f.write(f"# Cosmology: omega_m={omega_m} omega_b={omega_b} h0={h0}\n")
        f.write(f"# nk  na\n")
        f.write(f"{nk}  {na}\n")
        f.write(f"# k values (h/Mpc), log-spaced\n")
        for i, k in enumerate(k_arr):
            f.write(f"{k:.6e}")
            if (i + 1) % 10 == 0 or i == nk - 1:
                f.write("\n")
            else:
                f.write("  ")
        f.write(f"# a values (scale factor), log-spaced\n")
        for i, a in enumerate(a_arr):
            f.write(f"{a:.6e}")
            if (i + 1) % 10 == 0 or i == na - 1:
                f.write("\n")
            else:
                f.write("  ")
        f.write(f"# R_DE(k,a) matrix: nk rows x na columns\n")
        for ik in range(nk):
            for ia in range(na):
                f.write(f"{R_DE[ik, ia]:.6e}")
                if (ia + 1) % 10 == 0 or ia == na - 1:
                    f.write("\n")
                else:
                    f.write("  ")

    print(f"Done. Table shape: {nk} x {na}")
    print(f"k range: [{k_arr[0]:.2e}, {k_arr[-1]:.2e}] h/Mpc")
    print(f"a range: [{a_arr[0]:.4f}, {a_arr[-1]:.4f}]")
    print(f"R_DE range: [{R_DE.min():.6f}, {R_DE.max():.6f}]")

    # Verify: for cs2_de=0, R_DE should be k-independent at each a
    if cs2_de == 0.0:
        for ia in range(na):
            std_k = np.std(R_DE[:, ia])
            mean_k = np.mean(np.abs(R_DE[:, ia]))
            if mean_k > 1e-10 and std_k / mean_k > 0.01:
                print(f"  WARNING: cs2=0 but R_DE varies with k at a={a_arr[ia]:.4f}: "
                      f"std/mean={std_k/mean_k:.4f}")
        print("  cs2=0 check: R_DE should be k-independent (constant rows)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate DE transfer function table")
    parser.add_argument("--w0", type=float, default=-0.9, help="DE EOS w0 (default: -0.9)")
    parser.add_argument("--wa", type=float, default=0.1, help="DE EOS wa (default: 0.1)")
    parser.add_argument("--cs2", type=float, default=0.0, help="DE sound speed squared (default: 0.0)")
    parser.add_argument("--omega_m", type=float, default=0.3089, help="Omega_m (default: 0.3089)")
    parser.add_argument("--omega_b", type=float, default=0.0486, help="Omega_b (default: 0.0486)")
    parser.add_argument("--h0", type=float, default=0.6774, help="h (default: 0.6774)")
    parser.add_argument("-o", "--output", type=str, default="de_table.dat", help="Output file")
    parser.add_argument("--nk", type=int, default=200, help="Number of k points")
    parser.add_argument("--na", type=int, default=50, help="Number of a points")
    args = parser.parse_args()

    generate_de_table(
        output_file=args.output,
        w0=args.w0, wa=args.wa, cs2_de=args.cs2,
        omega_m=args.omega_m, omega_b=args.omega_b, h0=args.h0,
        nk=args.nk, na=args.na,
    )
